# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'Convert ATC Code for each patients to the corresponding DFS number of the ATC tree 
#'
#'@param tree : ATC tree (we assume that there is a column 'ATCCode' )
#'@param patients : patients observations, for each patient we got a string containing every medication he takes/took
#'@export
ATCtoNumeric <- function(patients, tree) {
    invisible(.Call(`_emcAdr_ATCtoNumeric`, patients, tree))
}

#'Convert the histogram returned by the DistributionApproximation function, to a real number ditribution
#'(that can be used in a test for example) 
#'
#'@param tree : ATC tree (we assume that there is a column 'ATCCode' )
#'@param patients : patients observations, for each patient we got a string containing every medication he takes/took
#'@export
histogramToDitribution <- function(vec) {
    .Call(`_emcAdr_histogramToDitribution`, vec)
}

#'The Evolutionary MCMC method that runs the random walk
NULL

#'The Evolutionary MCMC method that runs the random walk
NULL

#'The Evolutionary MCMC method that runs the random walk
#'
#'@param n : number of step 
#'@param ATCtree : ATC tree with upper bound of the DFS (without the root)
#'@param observation : real observation of the ADR based on the medications of each real patients
#'(a DataFrame containing the medication on the first column and the ADR (boolean) on the second)
#'
#'@param nbResults : number of results returned (best RR individuals), 5 by default
#'@param nbIndividuals : number on individuals in the population, 5 by default
#'@param startingIndividuals : starting individuals, randomly initialized by default 
#'(same form as the observations)
#'@param startingTemperatures : starting temperatures, randomly initialized by default
#'@param P_type1/P_type2/P_crossover : probability to operate respectively type1 mutation, type2 mutation and crossover. Note :
#'the probability to operate the swap is then 1 - sum(P_type1,P_type2,P_crossover). The sum must be less or equal to 1. 
#'@param alpha : a hyperparameter allowing us to manage to probability of adding a drug to the cocktail. The probability
#' to add a drug to the cocktail is the following : \eqn{\frac12}{\alpha/n} Where n is the original size of the cocktail. 1 is the default value.
#'
#'@return if no problem return an R List with : the distribution of RR we've met; bests individuals and the corresponding RRs. Otherwise the list is empty
#'@export
EMC <- function(n, ATCtree, observations, P_type1 = .25, P_type2 = .25, P_crossover = .25, nbIndividuals = 5L, nbResults = 5L, alpha = 1, startingIndividuals = NULL, startingTemperatures = NULL) {
    .Call(`_emcAdr_EMC`, n, ATCtree, observations, P_type1, P_type2, P_crossover, nbIndividuals, nbResults, alpha, startingIndividuals, startingTemperatures)
}

DistributionApproximation <- function(epochs, ATCtree, observations, temperature_M1 = 1L, temperature_M2 = 1L, Smax = 4L, p_type1 = .01) {
    .Call(`_emcAdr_DistributionApproximation`, epochs, ATCtree, observations, temperature_M1, temperature_M2, Smax, p_type1)
}

GeneticAlgorithm <- function(epochs, nbIndividuals, ATCtree, observations, p_crossover = .80, p_mutation = .01, nbElite = 0L, tournamentSize = 2L) {
    .Call(`_emcAdr_GeneticAlgorithm`, epochs, nbIndividuals, ATCtree, observations, p_crossover, p_mutation, nbElite, tournamentSize)
}

#'The true RR distribution of cocktail of size 2
#'
#'@param ATCtree : ATC tree with upper bound of the DFS (without the root)
#'@return the RR distribution among size 2 cocktail
#'@export
trueDistributionSizeTwoCocktail <- function(ATCtree, observations) {
    .Call(`_emcAdr_trueDistributionSizeTwoCocktail`, ATCtree, observations)
}

